.buildkite/deps-pipeline.yml
.buildkite/hooks/post-checkout
.gitignore
Cargo.lock
coverage_config_x86_64.json
resources/kernel/make_busybox.sh
resources/kernel/make_kernel.sh
resources/kernel/make_kernel_image.sh
src/vmm/Cargo.toml
src/vmm/src/boot.rs
src/vmm/src/config.rs
src/vmm/src/lib.rs
src/vmm/src/vcpu/mod.rs
src/vmm/tests/integration_tests.rs
src/vmm/tests/test_utils/mod.rs
tests/test_build_deps.py
tests/test_run_reference_vmm.py

#20
This PR introduces:
* bzImage changes in the reference VMM: the VMM will always try to load an ELF first, but if the kernel file is not an ELF, it will give bzImage a shot. Boot parameters and rip value are adjusted accordingly.
* revamp of the kernel image builder script: made it more modular, more parameterizable, and capable of baking the busybox initramfs in an ELF as well as a bzImage.
* integration test for the above script: it got complicated, so it kind of needed a test itself. However, the test takes a long time to run because it compiles kernels from scratch for multiple valid parameter combinations, so it's not run by the CI. It will be included in a long running tests battery instead.

bzImage kernel format support

---

coverage_config_x86_64.json
src/api/src/lib.rs
src/vmm/src/config/arg_parser.rs
src/vmm/src/config/builder.rs
src/vmm/src/config/mod.rs
src/vmm/src/lib.rs
src/vmm/tests/integration_tests.rs

Implemented `Builder` for `VMMConfig`. (Note: This is an early
implementation, more like prototype. But almost all functionality is
present.)
Removed `derive(Default)` from `MemoryConfig`, `KernelConfig` and
`VcpuConfig` and added sensible defaults (memory = 256M, vcpu=1) (derive
default will trivially initialize this to 0 and hence we are required to
take a memory coniguration from CLI launcher).
Brought these changes to `api` (`CLI`) to demonstrate a use.
Removed `required` from 'memory' and 'vcpu' config.
Changed `TryFrom<String>` to `TryFrom<&str>`. Believe this is better
because it's quite possible to get `&str` from `String` than other way
round and in fact often we'll get `&str` from CLI parsing etc. But the
other way round is painful.
Right now passes all 'existing' tests (`cargo …

Implementation of Builder pattern for Config

---

Cargo.lock
src/utils/src/lib.rs
src/vm-vcpu/Cargo.toml
src/vm-vcpu/src/vcpu/mod.rs
src/vmm/src/serial.rs

Defined a helper macro that prints errors only when in debug mode. This is necessary for situations in which we are dealing with potentially malicious input.
The macro is now used in two scenarios:
- for the serial console to print error messages regarding invalid reads/writes
- for handling errors in vcpu exits.

Use debug! macro instead of printlns and asserts

---

Cargo.lock
Cargo.toml
coverage_config_x86_64.json
src/devices/Cargo.toml
src/devices/src/virtio/block/device.rs
src/devices/src/virtio/block/mod.rs
src/devices/src/virtio/mod.rs
src/devices/src/virtio/net/bindings.rs
src/devices/src/virtio/net/device.rs
src/devices/src/virtio/net/mod.rs
src/devices/src/virtio/net/queue_handler.rs
src/devices/src/virtio/net/simple_handler.rs
src/devices/src/virtio/net/tap.rs
src/vm-vcpu/Cargo.toml
src/vmm/Cargo.toml
src/vmm/src/lib.rs

This PR refactors some of the common virtio device code to reduce the amount of required boilerplate, and then implements virtio net device support. The `tap` functionality and associated logic is taken from Firecracker for now, until we'll have a similar component available in rust-vmm or someplace else. More tests have to be added, and we're going to circle back to that after the initial version of the vsock support PR is ready as well.
Helpful steps for testing net device support:
- A `tap` device is needed on the host. One can be created and configured with something like (please note the example might conflict with the existing host configuration if there's overlap in terms of IP addresses/subnets):
```
sudo ip tuntap add dev vmtap100 mode tap
sudo ip addr add 192.168.241.1/24 dev …
```

Add net device support

---

src/vm-vcpu/src/vcpu/mod.rs

There is an unsafe block that can be considered unsafe.
Added a comment to justify why the unsafe block is safe.

vcpu: comment unsafe block

---

Cargo.lock
src/devices/Cargo.toml
src/devices/src/virtio/block/device.rs
src/devices/src/virtio/block/inorder_handler.rs
src/devices/src/virtio/block/mod.rs
src/devices/src/virtio/mod.rs
src/devices/src/virtio/net/device.rs
src/devices/src/virtio/net/simple_handler.rs

The vm-virtio paths need to be updated after vm-virtio was split into
several crates [here](https://github.com/rust-vmm/vm-virtio/pull/58)  .

Update vm-virtio paths

---

src/devices/src/virtio/block/mod.rs
tests/test_run_reference_vmm.py

This prevents the root fs from being mounted read-only
if no flags are given. Related to #46.

Explicitly add rw flag to cmdline for root

---

resources/kernel/make_kernel.sh

Update the `make_kernel` script to also support the PE format which is what Firecracker uses for arm64 microVMs.

Adjustments needed in make_kernel for using it in Firecracker

---

Cargo.lock
coverage_config_x86_64.json
src/vmm/Cargo.toml
src/vmm/src/lib.rs
src/vmm/src/serial.rs

Solves #125
Upgrade vm-superio to 0.3.0. As part of vm-superio changes, implemented the `Trigger` trait to be able to initialize the Serial Console. Initialized the devices using `NoEvents`

Upgrade vm-superio to 0.3.0

---

.buildkite/custom-tests.json

Updated the command that runs `test_run_reference_vmm.py` so that it includes a timeout in seconds per test. This means that each test will terminate and be marked as failed after the given timeout.

Add pytest timeout

---

README.md
docs/DESIGN.md
src/api/src/lib.rs
src/vmm/src/config/builder.rs
src/vmm/src/config/mod.rs
src/vmm/src/lib.rs
src/vmm/tests/integration_tests.rs
tests/test_run_reference_vmm.py

This patch is in preparation of adding aarch64 support. Naming the
field load_addr makes it a bit more platform independent.

rename high_mem_start to load_addr

---

Cargo.lock
coverage_config_x86_64.json
src/devices/Cargo.toml
src/devices/src/legacy/mod.rs
src/devices/src/legacy/rtc.rs
src/devices/src/legacy/serial.rs
src/devices/src/lib.rs
src/vmm/Cargo.toml
src/vmm/src/lib.rs

1. Changes to the Serial Console:
- Moved `serial.rs` to a new directory `src/devices/legacy`
- Implemented the MMIO trait for the `SerialWrapper`. Previously only the PIO trait was implemented, as on x86_64 the serial is available on the PIO bus. To enable support for aarch64, we needed to add it to the MMIO bus as well
2. Implemented the MMIO trait for `Rtc`, since this device is needed on aarch64.
3. Fixed the `read()` and `write()` functions for the serial device. Previously, these functions wouldn't return if the length of the array parameter `data` was not `1`; they would only log this and then try to access `data[0]`, even if `data` happened to be empty. Changed the functions so that they return after logging and updated the unit tests.

Add the Serial Console and RTC to the MMIO bus

---

Cargo.lock
Cargo.toml
coverage_config_x86_64.json
src/api/Cargo.toml
src/api/src/lib.rs
src/devices/Cargo.toml
src/vm-vcpu/Cargo.toml
src/vm-vcpu/src/vcpu/mptable.rs
src/vm-vcpu/src/vm.rs
src/vmm/Cargo.toml
src/vmm/src/config/builder.rs
src/vmm/src/config/mod.rs
src/vmm/src/lib.rs
src/vmm/tests/integration_tests.rs

This PR replaces the use of `String` with `linux_loader::Cmdline` for the `cmdline` member of the `KernelConfig` structure.
Fixes #98.

Use `linux_loader::Cmdline` instead of `String`

---

Cargo.lock
coverage_config_x86_64.json
src/vm-vcpu-ref/Cargo.toml
src/vm-vcpu-ref/coverage_config_x86_64.json
src/vm-vcpu-ref/src/lib.rs
src/vm-vcpu-ref/src/x86_64/gdt.rs
src/vm-vcpu-ref/src/x86_64/mod.rs
src/vm-vcpu/Cargo.toml
src/vm-vcpu/src/vcpu/mod.rs

This PR improves the GDT code to make it ready to be upstreamed. The approach is to move the code from vm-vcpu (which will contain the product specific code) to vm-vcpu-ref (which is the crate that's going to be published).
Then, future improvements are added directly in the vm-vcpu-ref code.
For some weird reason in tests I had to explicitly write the type of guest_memory to be `GuestMemoryMmap` because otherwise the tests will not compile with the error being that the `B` type corresponding to the Bitmap is missing.

Prepare gdt for upstream

---

Cargo.lock
src/vm-vcpu-ref/Cargo.toml
src/vm-vcpu-ref/coverage_config_x86_64.json
src/vm-vcpu-ref/src/x86_64/cpuid.rs
src/vm-vcpu-ref/src/x86_64/mod.rs
src/vm-vcpu/src/vcpu/mod.rs
src/vm-vcpu/src/vm.rs
src/vmm/Cargo.toml
src/vmm/src/lib.rs

This PR prepare the `cpuid` module for upstream. The first 3 commits should be ignored as they're part of #184. It was easier to continue the setup on top of those commits.
For the upstream, I've added tests, documentation, and some other tiny updates. More details in each corresponding commit.

Upstream cpuid

---

resources/kernel/configs.sh
resources/make_test_resources.sh

Using `uname -i` for detecting machine architecture is
problematic because it's not portable and returns
"unknown" on Debian and ArchLinux. Use `uname -m` instead.
Signed-off-by: Sergii Glushchenko <gsserge@amazon.com>

resources: properly detect machine architecture

---

coverage_config_x86_64.json
src/vm-vcpu-ref/coverage_config_x86_64.json
src/vm-vcpu-ref/src/x86_64/msrs.rs
src/vm-vcpu/src/vcpu/mod.rs
src/vm-vcpu/src/vm.rs
src/vmm/src/lib.rs

The point of this cleanup is to make it easier to work in parallel on extending the vm-vcpu interface with support  for save/restore on both platforms (aarch64 & x86_64), but also to work on upstreaming the `KvmVm` and `KvmVcpu` interfaces as part of vm-vcpu-ref.
The focus of this PR is not on having a complete implementation for save/restore, but to provide a high level design for it such that the work can be easily split among more people. As such, the save/restore functionality is not tested, this will be added as a follow up PR (coming after the vm-vcpu upstreaming).

Cleanup of the Vm & Vcpu interfaces (adding save/restore high level interface)

---

Cargo.lock
src/arch/Cargo.toml
src/devices/Cargo.toml
src/devices/src/virtio/block/device.rs
src/devices/src/virtio/block/inorder_handler.rs
src/devices/src/virtio/mod.rs
src/devices/src/virtio/net/device.rs
src/devices/src/virtio/net/simple_handler.rs
src/vm-vcpu-ref/Cargo.toml
src/vm-vcpu/Cargo.toml
src/vmm/Cargo.toml

Updated the virtio-queue, virtio-blk, virtio-device to the
commit d8ef45f and vm-memory 0.7.0.
Signed-off-by: Niculae Radu <r.niculae99@gmail.com>
The new virtio-queue implementation does not allow `Queue` to be cloned
since `QueueState` does not implement the `Clone` trait anymore.
The queues in `VirtioConfig` are removed after the configuration steps and
added to their corresponding handlers. 
requirements:
test.

Updated to latest virtio-queue and vm-memory 0.7.0

---

src/devices/src/legacy/i8042.rs
src/devices/src/legacy/mod.rs
src/vm-vcpu/src/vcpu/mod.rs
src/vmm/src/lib.rs
tests/test_run_reference_vmm.py

Signed-off-by: Ramyak Mehra <rmehra_be19@thapar.edu>
* Added I8042 wrapper inside devices/legacy.
* add_i8042_deive func inside src/vmm/lib.rs on the vmm struct.
* handled VcpuExit::IoOut at address i8042 port, inside vm-vcpu/src/vcpu/mod.rs
issue: #198 
requirements:
test.

consume i8042 device from vm-superio

---

src/vm-vcpu/src/vcpu/mod.rs
src/vm-vcpu/src/vcpu/regs.rs
src/vm-vcpu/src/vm.rs

* Save and restore per-vCPU state. For now only `mp_state` and all registers are saved. The set of saved items can be extended in future PRs if needed.
*  Implement bare bones `vm::set_state` and `vm::restore_state` and some basic testing.
* Clean up the `regs` module a bit.
Save and restore of `GIC` will be implemented in a future PR. Same goes for proper integration testing.
requirements:
test.

Save and restore vCPU state on aarch64

---

Cargo.lock
src/arch/src/lib.rs
src/devices/Cargo.toml
src/devices/src/virtio/block/device.rs
src/devices/src/virtio/mod.rs
src/vmm/src/lib.rs

Closes #210
Signed-off-by: Ramyak mehra <rmehra_be19@thapar.edu>
*Please summarize here why the changes in this PR are needed.*
requirements:
test.

Adding virtio support for arm

---

src/vm-vcpu-ref/src/aarch64/interrupts.rs
src/vm-vcpu-ref/src/aarch64/mod.rs
src/vm-vcpu-ref/src/aarch64/regs/dist.rs
src/vm-vcpu-ref/src/aarch64/regs/icc.rs
src/vm-vcpu-ref/src/aarch64/regs/mod.rs
src/vm-vcpu-ref/src/aarch64/regs/redist.rs
src/vm-vcpu/src/vm.rs

Save and restore the state of GIC (Generic Interrupt Controller) as part of the general VM state on aarch64.
The GIC state consists of three groups of registers:
1. Distributor registers, implemented in the `vm-vcpu-ref/aarch64/regs/dist` module.
2. Redistributors registers per vCPU, implemented in `vm-vcpu-ref/aarch64/regs/redist`.
3. System (ICC) registers per vCPU, implemented in `vm-vcpu-ref/aarch64/regs/icc`.
For redistributors and system registers, target vCPUs are identified by MPIDR registers, stored as part of the per-vCPU state. However, when doing `get attr` and `set attr` operations on a KVM device, the value of a MPIDR register should be packed in a specific way defined in https://www.kernel.org/doc/html/latest/virt/kvm/devices/arm-vgic-v3.html. The helper function …

GIC state save/restore

---

Cargo.lock
src/api/Cargo.toml
src/vm-vcpu-ref/src/x86_64/mptable.rs
src/vm-vcpu/src/vm.rs
src/vmm/src/irq_allocator.rs
src/vmm/src/lib.rs

We needed IRQAllocator for adding support
for multiple devices. IRQ_NUM for each platform is now passed
down through VMConfig. default value are used.
Signed-off-by: Ramyak mehra <rmehra_be19@thapar.edu>
*Please summarize here why the changes in this PR are needed.*
requirements:
test.

Implementing IRQAllocator in vmm
